# Generated by Django 5.2.6 on 2025-11-25 02:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_remove_aluno_turma_alter_aluno_cpf_responsavel_and_more'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['-data_inscricao'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_inscricao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Inscrição'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente')], default='ativo', max_length=20, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='turmas.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf_responsavel',
            field=models.CharField(max_length=11, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_responsavel',
            field=models.CharField(max_length=100, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero_responsavel',
            field=models.CharField(max_length=11, verbose_name='Telefone do Responsável'),
        ),
    ]
